name: Build rules

permissions:
  contents: write

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
  
      - name: Generate version tag
        id: generate_tag
        run: |
          VERSION=$(date +'%Y.%m.%d')
          echo "TAG=v$VERSION" >> $GITHUB_ENV

      - name: Create and push tag
        run: |
          git tag $TAG
          git push origin $TAG
        env:
          TAG: ${{ steps.generate_tag.outputs.TAG }}

      - name: Create rules
        run: |
          mkdir -p out
          touch out/Reject.list
          cat ConnersHua/Surge/Ruleset/Extra/Reject/* > out/Reject.list
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/Reject.list
          tag_name: ${{ steps.generate_tag.outputs.TAG }}
